#  群聊禁用功能（请勿手动修改）
#  help 帮助功能(/help /tkhelp)
#  bind 绑定功能(/bind /unbind)
#  b19 图片查分功能(/pgr /update /info /list /pb30 /score /lvsco /chap)
#  wb19 文字查分功能(/suggest /data /best)
#  song 图鉴功能(/song /ill /search /alias /rand)
#  ranklist 排行榜功能，不会禁用用户排名(/ranklist /godlist)
#  fnc 小功能(/com /tips)
#  tipgame tip猜歌(/tipgame)
#  guessgame 猜歌(/guess)
#  ltrgame 猜字母(/letter /ltr)
#  sign 娱乐功能(/sign /send /task /retask /jrrp)
#  setting 系统设置(/theme)
#  dan 段位认证相关(/dan /danupdate)